language: node_js
node_js:
  - 10
cache: npm

install: 
  - npm ci

script: 
  - npm test -- --watchAll=false

notification:
  email:
      recipients:
          - adamzopcsak@gmail.com
          - kgalmos@gmail.com
          - gyula.g.hodosi@gmail.com
      on_success: always
      on_failure: always
    